#!/bin/bash
env QUARTUS_ROOTDIR_OVERRIDE=${QDIR} \
    QSYS_ROOTDIR=${QDIR}/sopc_builder/bin \
    ALTERAOCLSDKROOT=${HOME}/local/altera/${QVERSION}/hld \
    PATH=${PATH}:${QDIR}/bin \
    ${QDIR}/bin/${QCMD} $*



